spring:
  redis:
    host: 192.168.200.130
    port: 6379
    password: QAQm..02r
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 1000
